apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: node-express
  namespace: default
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: node-express
    apps.tanzu.vmware.com/has-tests: true
spec:
  source:
    git:
      #url: https://github.com/vmware-tanzu/application-accelerator-samples
      url : https://github.com/myminseok/tanzu-workload-samples
      subPath: /node-express
      ref:
        branch: main
  params:
  ## https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.6/tap/scc-ootb-supply-chain-testing.html multiple testing pipeline
  - name: testing_pipeline_matching_labels
    value:
      apps.tanzu.vmware.com/pipeline: test
      apps.tanzu.vmware.com/language: nodejs